name: CI

on: [pull_request]

jobs:
  test:
    environment: eaidashboard
    runs-on: ubuntu-latest
    env:
      PG_USR: ${{ secrets.PG_USR }}
      PG_PWD: ${{ secrets.PG_PWD }}
      PG_URL: ${{ secrets.PG_URL }}
      PG_PORT: ${{ secrets.PG_PORT }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      TIMEDELTA: 3600
      SESSION_KEY: ${{ secrets.SESSION_KEY }}
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.PG_USR }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PWD }}
          POSTGRES_DB: testdb
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Run tests with coverage
        env:
          PG_USR: postgres
          PG_PWD: postgres
          PG_URL: localhost
          PG_PORT: 5432
          REDIS_URL: localhost
          REDIS_PORT: 6379
          TIMEDELTA: 3600
          SESSION_KEY: poiuytrezz
        run: |
            mkdir app/static
            poetry run coverage run -m pytest
            poetry run coverage xml
            poetry run coverage report
            poetry run coverage-badge -o coverage.svg
        continue-on-error: true
      - name: Commit badge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add coverage.svg
            git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
            git push
