name: CI-push

on: [push]

jobs:
  test:
    environment: eaidashboard
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Lint
        uses: chartboost/ruff-action@v1
        with:
          src: "./app"
      - name: Run tests with coverage
        env:
          PG_USR: postgres
          PG_PWD: postgres
          PG_URL: localhost
          PG_PORT: 5432
          REDIS_URL: localhost
          REDIS_PORT: 6379
          TIMEDELTA: 3600
          SESSION_KEY: poiuytrezz
        run: |
            mkdir app/static
            poetry run coverage run -m pytest
            poetry run coverage xml
        continue-on-error: true
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          output: both
          format: markdown